language: python

cache:
    apt
    pip
python:
  - 2.7
  - pypy
env:
    - pep8
before_install:
  - sudo apt-get install python-pip
  - pip install tox

matrix:
  exclude:
    - python: 2.7
      env: pep8

script: tox -e pep8

